server:
  port: 8082

spring:
  profiles:
    active: qa


---

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp
    password: Parolaptmysql2.0
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    activate:
      on-profile: dev
welcome:
  message: Welcome to SpringBoot!!!!

---

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp-qa
    password: Parolaptmysql2.0
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    activate:
      on-profile: qa
welcome:
  message: Welcome to SpringBoot!!!!
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"

---

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/dcbapp-prod
    password: Parolaptmysql2.0
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    activate:
      on-profile: prod
welcome:
  message: Welcome to SpringBoot!!!!

